"""Run the Phase-4 multi-quarter headline backtest for a variant and persist the artifacts.

Headline metric (Phase 4.0 gate): for each quarter, the nowcast at the as-of
``(advance_date - 1 day)`` PRE-ADVANCE cutoff vs the BEA advance estimate;
error = advance - nowcast (NY-Fed style). 2020 (q1-q4) is reported separately as it is a
known outlier regime (Phase 7 handles it); the ex-2020 sample is the headline number.

Writes:
  outputs/<variant>/weekly/<period>.csv  -- per-quarter weekly nowcast path (gitignored)
  outputs/<variant>/headline.csv         -- per-quarter headline vs advance (gitignored)
  docs/dashboard_data/<variant>.json     -- committed durable artifact (feeds the dashboard)
  docs/results.md                        -- committed: the headline RMSE/MAE table(s)

M1 guard: asserts every wired quarter has a non-None headline (else a forgotten
build_headline_vintages run would silently drop it).

Usage (from repo root):
  uv run python -m tools.run_backtest --variant baseline --workers 4
  uv run python -m tools.run_backtest --variant baseline --periods 2017q1,2018q1 --workers 2
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from gdpnowcast.metrics import summarize
from gdpnowcast.nowcast.backtest import run_backtest

REPO = Path(__file__).resolve().parents[1]
VARIANT_CFG = {
    "baseline": ("US_new", "Spec_US_new.xlsx"),
    "fiscal": ("US_fiscal", "Spec_US_fiscal.xlsx"),
}
COVID = {"2020q1", "2020q2", "2020q3", "2020q4"}
DASHBOARD_DATA = REPO / "docs" / "dashboard_data"


def _write_artifacts(variant: str, results: list[dict]) -> pd.DataFrame:
    out_dir = REPO / "outputs" / variant
    (out_dir / "weekly").mkdir(parents=True, exist_ok=True)
    head_rows = []
    for r in results:
        pd.DataFrame(r["weekly"]).to_csv(out_dir / "weekly" / f"{r['period']}.csv", index=False)
        h = r["headline"]
        head_rows.append(
            {
                "period": r["period"],
                "advance_date": r["advance_date"],
                "gdp_advance": float(r["gdp_actual"]),
                "headline_nowcast": float(h["y_new"]),
                "error": float(h["error"]),
                "abs_error": abs(float(h["error"])),
            }
        )
    head = pd.DataFrame(head_rows)
    head.to_csv(out_dir / "headline.csv", index=False)

    err_all = head["error"].tolist()
    err_ex = head.loc[~head["period"].isin(COVID), "error"].tolist()
    metrics = {"all": summarize(err_all), "ex_2020": summarize(err_ex)}

    DASHBOARD_DATA.mkdir(parents=True, exist_ok=True)
    (DASHBOARD_DATA / f"{variant}.json").write_text(
        json.dumps(
            {
                "variant": variant,
                "headline": head_rows,
                "weekly": {r["period"]: r["weekly"] for r in results},
                "skipped": {r["period"]: r["skipped"] for r in results},
                "metrics": metrics,
            },
            indent=2,
            default=float,
        )
        + "\n",
        encoding="utf-8",
    )
    return head


def _fmt_metrics(m: dict[str, dict[str, float]]) -> str:
    rows = ["| sample | n | RMSE | MAE | Bias |", "|---|---|---|---|---|"]
    for label, key in (("all quarters", "all"), ("ex-2020", "ex_2020")):
        s = m[key]
        rows.append(
            f"| {label} | {int(s['n'])} | {s['rmse']:.3f} | {s['mae']:.3f} | {s['bias']:+.3f} |"
        )
    return "\n".join(rows)


def _regenerate_results_md() -> None:
    """Assemble docs/results.md from whatever <variant>.json artifacts exist."""
    lines = [
        "# Headline backtest results",
        "",
        "Headline metric (Phase 4.0 gate decision): for each quarter, the DFM nowcast at the",
        "as-of **(advance_date - 1 day)** pre-advance cutoff -- the tightest as-of that provably",
        "excludes the BEA GDP advance and its same-day co-releases -- scored against the BEA",
        "advance estimate. `error = advance - nowcast`; `Bias > 0` means the nowcast under-predicts.",
        "2020 (q1-q4) is a known outlier regime (Phase 7); **ex-2020 is the headline sample**.",
        "",
        "_Generated by `tools/run_backtest.py`; data in `docs/dashboard_data/<variant>.json`._",
        "",
    ]
    for variant in ("baseline", "fiscal"):
        p = DASHBOARD_DATA / f"{variant}.json"
        title = "Baseline (no fiscal)" if variant == "baseline" else "Fiscal (with fiscal series)"
        lines.append(f"## {title}")
        lines.append("")
        if not p.exists():
            lines += ["_pending._", ""]
            continue
        data = json.loads(p.read_text(encoding="utf-8"))
        lines.append(_fmt_metrics(data["metrics"]))
        lines.append("")
        lines.append("| quarter | advance date | advance | nowcast | error |")
        lines.append("|---|---|---|---|---|")
        for h in data["headline"]:
            lines.append(
                f"| {h['period']} | {h['advance_date']} | {h['gdp_advance']:+.1f} | "
                f"{h['headline_nowcast']:+.3f} | {h['error']:+.3f} |"
            )
        lines.append("")
    lines += [
        "## Notes",
        "",
        "- **2025q1 weekly path**: the v1 source (`nowcast_2025.py`) omitted four Fridays "
        "(2025-03-28 ... 2025-04-18) from the 2025q1 vintage list; the registry now includes "
        "them (completed in the Phase-5 dashboard step via `tools/refresh_period_weekly`, which "
        "pins the headline). The headline (advance-1) nowcast is a standalone vintage and was "
        "unchanged by the addition.",
        "- The large ex-2020 misses (2022q1/q2, 2025q1) are genuine real-economy surprises "
        "(inventory/net-export-driven contractions the monthly-indicator DFM does not see), not "
        "code/data artifacts -- confirmed by adversarial review.",
        "",
    ]
    (REPO / "docs" / "results.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", choices=tuple(VARIANT_CFG), default="baseline")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--periods", default="", help="comma-separated subset, e.g. 2017q1,2018q1")
    args = ap.parse_args()

    subdir, spec = VARIANT_CFG[args.variant]
    periods = [p for p in args.periods.split(",") if p] or None
    print(
        f"running {args.variant} backtest (workers={args.workers}, periods={periods or 'ALL'}) ..."
    )
    results = run_backtest(subdir, spec, periods=periods, workers=args.workers)

    missing = [r["period"] for r in results if r["headline"] is None]
    if missing:
        raise SystemExit(
            f"headline=None for {missing} -- run `uv run python -m tools.build_headline_vintages`"
        )

    head = _write_artifacts(args.variant, results)
    _regenerate_results_md()

    err_all = head["error"].tolist()
    err_ex = head.loc[~head["period"].isin(COVID), "error"].tolist()
    print(f"\n{args.variant}: {len(head)} quarters")
    print("all   ", summarize(err_all))
    print("ex2020", summarize(err_ex))
    print(f"wrote docs/dashboard_data/{args.variant}.json + docs/results.md")


if __name__ == "__main__":
    main()
